payloads/external/sortbootorder: rewrite the Makefile and add Kconfig
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>

diff --git a/payloads/external/sortbootorder/Makefile b/payloads/external/sortbootorder/Makefile
--- a/payloads/external/sortbootorder/Makefile
+++ b/payloads/external/sortbootorder/Makefile
@@ -1,7 +1,10 @@
-version=4.6.16
-branch_name=v$(version)
-project_url=https://github.com/pcengines/sortbootorder/archive/$(branch_name).tar.gz
-archive_name=$(branch_name).tar.gz
+TAG-$(SORTBOOTORDER_MASTER)=origin/master
+TAG-$(SORTBOOTORDER_STABLE)=v4.6.17
+TAG-$(SORTBOOTORDER_REVISION)=$(SORTBOOTORDER_REVISION_ID)
+
+project_git_repo=https://github.com/pcengines/sortbootorder.git
+project_name=sortbootorder
+project_dir=$(CURDIR)/sortbootorder
 
 unexport KCONFIG_AUTOHEADER
 unexport KCONFIG_AUTOCONFIG
@@ -10,17 +13,33 @@ unexport KCONFIG_SPLITCONFIG
 unexport KCONFIG_TRISTATE
 unexport KCONFIG_NEGATIVES
 
-all: sortbootorder
+all: build
 
-sortbootorder: download
-	echo "    MAKE       sortbootorder     "
-	$(MAKE) -C sortbootorder VERSION=$(branch_name) APU1=$(TARGET_APU1)
+$(project_dir):
+	echo "    Cloning sortbootorder from Git"
+	git clone $(project_git_repo) $(project_dir)
 
-download:
-	test -d sortbootorder || { wget $(project_url); \
-		tar -xvf $(archive_name); \
-		rm $(archive_name); \
-		mv sortbootorder-$(version) sortbootorder; }
+fetch: $(project_dir)
+ifeq ($(TAG-y),)
+	echo "Error: The specified tag is invalid"
+ifeq ($(SORTBOOTORDER_REVISION),y)
+	echo "Error: There is no revision specified for sortbootorder"
+	false
+endif
+	false
+endif
+	cd sortbootorder; git show $(TAG-y) >/dev/null 2>&1 ; \
+		if [ $$? -ne 0 ] || [ "$(TAG-y)" = "origin/master" ]; then \
+		echo "    Fetching new commits from the sortbootorder repo"; \
+		git fetch; fi
+
+checkout: fetch
+	echo "    Checking out sortbootorder revision $(TAG-y)"
+	cd sortbootorder; git checkout master; git branch -D coreboot 2>/dev/null; git checkout -b coreboot $(TAG-y)
+
+build: checkout
+	echo "    MAKE       sortbootorder"
+	$(MAKE) -C sortbootorder VERSION=$(TAG-y) APU1=$(TARGET_APU1)
 
 clean:
 	test -d sortbootorder && $(MAKE) -C sortbootorder clean || exit 0
@@ -28,4 +47,7 @@ clean:
 distclean:
 	rm -rf sortbootorder
 
-.PHONY: download patch sortbootorder clean distclean
+print-repo-info:
+	echo "$(project_git_repo) $(project_dir)"
+
+.PHONY: checkout build clean distclean fetch sortbootorder print-repo-info
